### ISSUE TITLE
Upgrade peerDependencies to latest and upgrade tests to MongoDb 4.2

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-profile-http#13]
Many `peerDepedencies` of this package have recently received a major release.

In particular `peerDepedencies` will need to follow this pattern `lastRelease.x - latestRelease.x`.

Documentation on peerDeps can be found here: https://nodejs.org/en/blog/npm/peer-dependencies/

The latest major releases are:

`bedrock-kms: ^3.0.0`
`bedrock-edv-storage: ^3.0.0`
`bedrock-session-mongodb: ^4.0.0`
`bedrock-identity: ^8.0.0`
`bedrock-vc-issuer: ^4.0.0`
`bedrock-ssm-mongodb: ^3.0.0`
`bedrock-zcap-storage: ^3.0.0`
`bedrock-authn-token: ^2.0.0`
`bedrock-profile: ^5.00`
`bedrock-account: ^3.0.0`
`bedrock-permission: ^3.0.0`

You will also need to upgrade the test project.
This should require 2 steps:
1. Update the test dependencies to the latest releases.
2. Change the `.github/workflows/main.yml` so that MongoDb is version 4.2

This Draft PR can be used a model: https://github.com/digitalbazaar/bedrock-kms-http/pull/25

**Comment by mandyvenables** [comment]
PR #14 was merged successfully.
