### ISSUE TITLE
Add zcap-based admin API

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-profile-http#20]
Per this [TODO](https://github.com/digitalbazaar/bedrock-profile-http/blob/master/lib/http.js#L44)

**Comment by mandyvenables** [comment]
@dlongley priority?

**Comment by dlongley** [comment]
I think this is priority 3+ ... not sure how we're classifying those, but it's not 1 or 2.

**Comment by dlongley** [comment]
Closing as it's not clear if / when this would occur or if it would happen via another means.
