### ISSUE TITLE
Thoroughly document major release/breaking changes.

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-profile-http#26]
https://github.com/digitalbazaar/bedrock-profile-http/blob/master/CHANGELOG.md#500---2020-09-25

@aljones15 are you willing to pick up this one?

**Comment by aljones15** [comment]
@mattcollier I assigned this to myself so I see it in the future. If you think an issue is suited to me just assign to me if no one else wants to take it sooner.

**Comment by dlongley** [comment]
Closing as over 1.5 years old and many major breaking releases have occurred (and have been documented) since.
